import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <div>
            <Link href='/' legacyBehavior >
              <a> Home </a>
            </Link>
            <Link href='/events' legacyBehavior >
              <a> Events </a>
            </Link>
            <Link href='/about-us' legacyBehavior >
              <a> About Us </a>
            </Link>
          </div>
        </nav>
      </header>
      <main >
        {data.map((ev) => (
          <Link key={ev.id} href={`/events/${ev.id}`} passHref>
            <div >
              <Image width={300} height={300} alt={ev.title} src={ev.image} />
              <h2>{ev.title}</h2>
              <p>
                {ev.description}
              </p>
            </div>
          </Link>

        ))}
      </main>

      <footer className={styles.footer}>
        <p>2022 time to code </p>
      </footer>
    </>
  )
}

export async function getServerSideProps() {
  // never run in the client
  // Run before the component ever exist 
  // https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props
  const { events_categories } = await import('/data/data.json');

  return {
    props: {
      data: events_categories
    }
  }
}

